### ISSUE TITLE
volume adjustment not working

### ISSUE THREAD

**Issue by welpdx** [paulopacitti/onsen#1]
On Windows 11 22H2 on command prompt, adjusting the volume via `volume xx` doesn't seem to affect the volume level. 
e.g., `volume 0` does not lead to no sound.

**Comment by paulopacitti** [comment]
Unfortunately, I don't have Windows developing machine to test this issue :( It must be an issue with `pygame`, which is the lib that play sounds. Feel free to open a PR in case you find the solution :)

**Comment by welpdx** [comment]
@paulopacitti ok thanks for the quick reply! I will look into it when I have time.

**Comment by welpdx** [comment]
ok it is my bad! I thought the way to change volume is to enter `volume xx` instead of what is shown in the demo: `volume` -> enter integer!

I have a made an enhancement pr #3. not a biggie though
