### ISSUE TITLE
[Enhancement] on console close via clicking on the x leads to end of sound

### ISSUE THREAD

**Issue by welpdx** [paulopacitti/onsen#2]
On Windows 11 22H2 on command prompt, closing the console while the rain is still playing leads to that sound persisting even though console is closed. 

Suggestion to end the sound like `quit` when user clicks on the x button.

---
Btw, this is an absolutely bomber of a project! I love it~ 
:D

**Comment by paulopacitti** [comment]
Hey, thanks a lot! ✨ I started this project but I didn't like the the result that I got at first hahahahaha I need to improve the rain sound itself to make more vivid and seamless loopable.

About the issue, I think I can work on this `quit` Python routine to make sure the sound stops, thanks for the suggestion :)

**Comment by welpdx** [comment]
Looking forward to the improvements you will make!

This project is clean bro! Clean! I love the UI and how neat and organized the readme is!

**Comment by welpdx** [comment]
Gonna close this issue because after a restart, I couldn't reproduce the issue. Might be just me.
